# Generated by Django 5.2.1 on 2025-06-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
