# Generated by Django 5.2.1 on 2025-06-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_language_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='learning_languages',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='native_language',
        ),
    ]
