# Generated by Django 5.2.1 on 2025-06-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguage',
            name='proficiency',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('native', 'Native'), ('fluent', 'Fluent')], max_length=20),
        ),
    ]
