# Generated by Django 5.2.1 on 2025-07-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_google_login',
            field=models.BooleanField(default=False),
        ),
    ]
