# Generated by Django 5.2.1 on 2025-07-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usersubscriptionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_google_login',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('report', 'New Report'), ('user_registration', 'New User Registration'), ('system_update', 'System Update'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('banned', 'Banned'), ('flagged', 'Flagged')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_status',
            field=models.CharField(db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersubscriptionhistory',
            name='payment_status',
            field=models.CharField(db_index=True, default='paid', max_length=50),
        ),
    ]
