# Generated by Django 5.2.1 on 2025-06-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='video_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
