# Generated by Django 5.2.1 on 2025-07-04 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_is_deleted_reportedroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
