# Generated by Django 5.2.1 on 2025-07-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedroom',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('suspend', 'suspend')], default='pending', max_length=20),
        ),
    ]
