# Generated by Django 5.2.1 on 2025-07-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_reportedroom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
