# Generated by Django 5.2.1 on 2025-07-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_room_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedroom',
            name='custom_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportedroom',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam or unwanted messages'), ('misbehavior', 'Inappropriate behavior'), ('harassment', 'Harassment or bullying'), ('inappropriate_content', 'Inappropriate content'), ('fake_identity', 'Fake identity or impersonation'), ('disruptive', 'Disrupting conversations'), ('hate_speech', 'Hate speech or discrimination'), ('other', 'Other (please specify)')], max_length=50),
        ),
    ]
