# Generated by Django 5.2.1 on 2025-07-22 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_reportedroom_custom_description_and_more'),
        ('users', '0008_alter_customuser_is_google_login_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reportedroom',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('suspend', 'suspend')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportedroom',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('ended', 'Ended'), ('scheduled', 'Scheduled')], db_index=True, default='live', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='left_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('cohost', 'Co-host'), ('participant', 'Participant')], db_index=True, default='participant', max_length=20),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'sent_at'], name='rooms_messa_room_id_0dab23_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status', 'is_deleted'], name='rooms_room_status_bf2bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='roomparticipant',
            index=models.Index(fields=['room', 'user'], name='rooms_roomp_room_id_c911db_idx'),
        ),
    ]
